FROM golang:1.11

RUN go get github.com/wrlou/delinkcious/...

WORKDIR /go/src/github.com/wrlou/delinkcious/svc/social_graph_service
ADD ./main.go main.go

# Update
RUN apt-get --allow-releaseinfo-change update && apt upgrade -y

# Fetch dependencies
RUN go get -d -v

ADD ./service service

RUN CGO_ENABLED=0 GOOS=linux go build -o /social_graph_service -a -tags netgo -ldflags '-s -w' .

EXPOSE 8080
ENTRYPOINT ["/social_graph_service"]
